# whats_app_cloud_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module WhatsAppCloudApi
  # ButtonParameterType.
  class ButtonParameterTypeEnum
    BUTTON_PARAMETER_TYPE_ENUM = [
      # TODO: Write general description for PAYLOAD
      PAYLOAD = 'payload'.freeze,

      # TODO: Write general description for TEXT
      TEXT = 'text'.freeze
    ].freeze
  end
end
