# whats_app_cloud_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module WhatsAppCloudApi
  # ComponentType.
  class ComponentTypeEnum
    COMPONENT_TYPE_ENUM = [
      # TODO: Write general description for HEADER
      HEADER = 'header'.freeze,

      # TODO: Write general description for BODY
      BODY = 'body'.freeze,

      # TODO: Write general description for BUTTON
      BUTTON = 'button'.freeze
    ].freeze
  end
end
