# whats_app_cloud_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module WhatsAppCloudApi
  # Currency Model.
  class Currency < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Default text if localization fails.
    # @return [String]
    attr_accessor :fallback_value

    # Currency code as defined in ISO 4217.
    # @return [String]
    attr_accessor :code

    # Amount multiplied by 1000.
    # @return [Integer]
    attr_accessor :amount_1000

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['fallback_value'] = 'fallback_value'
      @_hash['code'] = 'code'
      @_hash['amount_1000'] = 'amount_1000'
      @_hash
    end

    # An array for optional fields
    def optionals
      []
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(fallback_value = nil,
                   code = nil,
                   amount_1000 = nil)
      @fallback_value = fallback_value unless fallback_value == SKIP
      @code = code unless code == SKIP
      @amount_1000 = amount_1000 unless amount_1000 == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      fallback_value =
        hash.key?('fallback_value') ? hash['fallback_value'] : SKIP
      code = hash.key?('code') ? hash['code'] : SKIP
      amount_1000 = hash.key?('amount_1000') ? hash['amount_1000'] : SKIP

      # Create object from extracted values.
      Currency.new(fallback_value,
                   code,
                   amount_1000)
    end
  end
end
