# whats_app_cloud_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module WhatsAppCloudApi
  # HeaderType.
  class HeaderTypeEnum
    HEADER_TYPE_ENUM = [
      # Used for List Messages and Reply Buttons.
      TEXT = 'text'.freeze,

      # Used for Reply Buttons.
      DOCUMENT = 'document'.freeze,

      # Used for Reply Buttons.
      IMAGE = 'image'.freeze,

      # Used for Reply Buttons.
      VIDEO = 'video'.freeze
    ].freeze
  end
end
