# whats_app_cloud_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module WhatsAppCloudApi
  # Image Model.
  class Image < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The media object ID. Required when you are not using a link.
    # @return [String]
    attr_accessor :id

    # The protocol and URL of the media to be sent. Use only with HTTP/HTTPS
    # URLs. Required when you are not using an uploaded media ID.
    # @return [String]
    attr_accessor :link

    # Describes the specified image media.
    # @return [String]
    attr_accessor :caption

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['id'] = 'id'
      @_hash['link'] = 'link'
      @_hash['caption'] = 'caption'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        id
        link
        caption
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(id = nil,
                   link = nil,
                   caption = nil)
      @id = id unless id == SKIP
      @link = link unless link == SKIP
      @caption = caption unless caption == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      id = hash.key?('id') ? hash['id'] : SKIP
      link = hash.key?('link') ? hash['link'] : SKIP
      caption = hash.key?('caption') ? hash['caption'] : SKIP

      # Create object from extracted values.
      Image.new(id,
                link,
                caption)
    end
  end
end
