# whats_app_cloud_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module WhatsAppCloudApi
  # The type of interactive message you want to send.
  class InteractiveTypeEnum
    INTERACTIVE_TYPE_ENUM = [
      # TODO: Write general description for LIST
      LIST = 'list'.freeze,

      # TODO: Write general description for BUTTON
      BUTTON = 'button'.freeze
    ].freeze
  end
end
