# whats_app_cloud_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module WhatsAppCloudApi
  # Language Model.
  class Language < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The code of the language or locale to use. Accepts both language and
    # language_locale formats (e.g., en and en_US).
    # @return [String]
    attr_accessor :code

    # The language policy the message should follow.
    # @return [String]
    attr_accessor :policy

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['code'] = 'code'
      @_hash['policy'] = 'policy'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        policy
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(code = nil,
                   policy = 'deterministic')
      @code = code unless code == SKIP
      @policy = policy unless policy == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      code = hash.key?('code') ? hash['code'] : SKIP
      policy = hash['policy'] ||= 'deterministic'

      # Create object from extracted values.
      Language.new(code,
                   policy)
    end
  end
end
