# whats_app_cloud_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module WhatsAppCloudApi
  # MessageType.
  class MessageTypeEnum
    MESSAGE_TYPE_ENUM = [
      # TODO: Write general description for TEXT
      TEXT = 'text'.freeze,

      # TODO: Write general description for AUDIO
      AUDIO = 'audio'.freeze,

      # TODO: Write general description for CONTACTS
      CONTACTS = 'contacts'.freeze,

      # TODO: Write general description for DOCUMENT
      DOCUMENT = 'document'.freeze,

      # TODO: Write general description for IMAGE
      IMAGE = 'image'.freeze,

      # TODO: Write general description for INTERACTIVE
      INTERACTIVE = 'interactive'.freeze,

      # TODO: Write general description for LOCATION
      LOCATION = 'location'.freeze,

      # TODO: Write general description for STICKER
      STICKER = 'sticker'.freeze,

      # TODO: Write general description for TEMPLATE
      TEMPLATE = 'template'.freeze,

      # TODO: Write general description for VIDEO
      VIDEO = 'video'.freeze
    ].freeze
  end
end
