# whats_app_cloud_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module WhatsAppCloudApi
  # ParameterType.
  class ParameterTypeEnum
    PARAMETER_TYPE_ENUM = [
      # TODO: Write general description for TEXT
      TEXT = 'text'.freeze,

      # TODO: Write general description for CURRENCY
      CURRENCY = 'currency'.freeze,

      # TODO: Write general description for DATE_TIME
      DATE_TIME = 'date_time'.freeze,

      # TODO: Write general description for IMAGE
      IMAGE = 'image'.freeze,

      # TODO: Write general description for DOCUMENT
      DOCUMENT = 'document'.freeze,

      # TODO: Write general description for VIDEO
      VIDEO = 'video'.freeze
    ].freeze
  end
end
