# whats_app_cloud_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module WhatsAppCloudApi
  # PersonalInformationType.
  class PersonalInformationTypeEnum
    PERSONAL_INFORMATION_TYPE_ENUM = [
      # TODO: Write general description for HOME
      HOME = 'HOME'.freeze,

      # TODO: Write general description for WORK
      WORK = 'WORK'.freeze
    ].freeze
  end
end
