# whats_app_cloud_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module WhatsAppCloudApi
  # PhoneType.
  class PhoneTypeEnum
    PHONE_TYPE_ENUM = [
      # TODO: Write general description for HOME
      HOME = 'HOME'.freeze,

      # TODO: Write general description for WORK
      WORK = 'WORK'.freeze,

      # TODO: Write general description for CELL
      CELL = 'CELL'.freeze,

      # TODO: Write general description for MAIN
      MAIN = 'MAIN'.freeze,

      # TODO: Write general description for IPHONE
      IPHONE = 'IPHONE'.freeze
    ].freeze
  end
end
