# whats_app_cloud_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module WhatsAppCloudApi
  # PhoneObject Model.
  class PhoneObject < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Automatically populated with the wa_id value as a formatted phone number.
    # @return [String]
    attr_accessor :phone

    # WhatsApp ID.
    # @return [String]
    attr_accessor :wa_id

    # WhatsApp ID.
    # @return [PhoneTypeEnum]
    attr_accessor :type

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['phone'] = 'phone'
      @_hash['wa_id'] = 'wa_id'
      @_hash['type'] = 'type'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        phone
        wa_id
        type
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(phone = nil,
                   wa_id = nil,
                   type = nil)
      @phone = phone unless phone == SKIP
      @wa_id = wa_id unless wa_id == SKIP
      @type = type unless type == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      phone = hash.key?('phone') ? hash['phone'] : SKIP
      wa_id = hash.key?('wa_id') ? hash['wa_id'] : SKIP
      type = hash.key?('type') ? hash['type'] : SKIP

      # Create object from extracted values.
      PhoneObject.new(phone,
                      wa_id,
                      type)
    end
  end
end
