# whats_app_cloud_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module WhatsAppCloudApi
  # For more information relating to quality rating, see [About WhatsApp
  # Business Account Message Quality
  # Rating](https://www.facebook.com/business/help/896873687365001).
  class QualityRatingEnum
    QUALITY_RATING_ENUM = [
      # High Quality.
      GREEN = 'GREEN'.freeze,

      # Medium Quality.
      YELLOW = 'YELLOW'.freeze,

      # Low Quality.
      RED = 'RED'.freeze,

      # Quality has not been determined.
      NA = 'NA'.freeze
    ].freeze
  end
end
