# whats_app_cloud_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module WhatsAppCloudApi
  # RequestVerificationCodeMethod.
  class RequestVerificationCodeMethodEnum
    REQUEST_VERIFICATION_CODE_METHOD_ENUM = [
      # TODO: Write general description for SMS
      SMS = 'SMS'.freeze,

      # TODO: Write general description for VOICE
      VOICE = 'VOICE'.freeze
    ].freeze
  end
end
