# whats_app_cloud_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module WhatsAppCloudApi
  # Section Model.
  class Section < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Required if the message has more than one section. Title of the section.
    # @return [String]
    attr_accessor :title

    # Required for List Messages. Contains a list of rows. You can have a total
    # of 10 rows across your sections. Each row must have a title (Maximum
    # length: 24 characters) and an ID (Maximum length: 200 characters). You can
    # add a description (Maximum length: 72 characters), but it is optional.
    # @return [List of Row]
    attr_accessor :rows

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['title'] = 'title'
      @_hash['rows'] = 'rows'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        title
        rows
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(title = nil,
                   rows = nil)
      @title = title unless title == SKIP
      @rows = rows unless rows == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      title = hash.key?('title') ? hash['title'] : SKIP
      # Parameter is an array, so we need to iterate through it
      rows = nil
      unless hash['rows'].nil?
        rows = []
        hash['rows'].each do |structure|
          rows << (Row.from_hash(structure) if structure)
        end
      end

      rows = SKIP unless hash.key?('rows')

      # Create object from extracted values.
      Section.new(title,
                  rows)
    end
  end
end
