# whats_app_cloud_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module WhatsAppCloudApi
  # A 6-digit pin you wish to use for two-step authentication.
  class SetTwoStepVerificationCodeRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :pin

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['pin'] = 'pin'
      @_hash
    end

    # An array for optional fields
    def optionals
      []
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(pin = nil)
      @pin = pin unless pin == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      pin = hash.key?('pin') ? hash['pin'] : SKIP

      # Create object from extracted values.
      SetTwoStepVerificationCodeRequest.new(pin)
    end
  end
end
