# whats_app_cloud_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module WhatsAppCloudApi
  # SubType.
  class SubTypeEnum
    SUB_TYPE_ENUM = [
      # Refers to a previously created quick reply button that allows for the
      # customer to return a predefined message.
      QUICKREPLY = 'quick_reply'.freeze,

      # Refers to a previously created button that allows the customer to visit
      # the URL generated by appending the text parameter to the predefined
      # prefix URL in the template.
      URL = 'url'.freeze
    ].freeze
  end
end
