# whats_app_cloud_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module WhatsAppCloudApi
  # Text Model.
  class Text < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Required for text messages. The text of the text message which can contain
    # URLs which begin with http:// or https:// and formatting. See available
    # formatting options here. If you include URLs in your text and want to
    # include a preview box in text messages (preview_url: true), make sure the
    # URL starts with http:// or https:// —https:// URLs are preferred. You must
    # include a hostname, since IP addresses will not be matched.
    # @return [String]
    attr_accessor :body

    # By default, WhatsApp recognizes URLs and makes them clickable, but you can
    # also include a preview box with more information about the link. Set this
    # field to true if you want to include a URL preview box. The majority of
    # the time, the receiver will see a URL they can click on when you send an
    # URL, set preview_url to true, and provide a body object with a http or
    # https link. URL previews are only rendered after one of the following has
    # happened: The business has sent a message template to the user. The user
    # initiates a conversation with a "click to chat" link. The user adds the
    # business phone number to their address book and initiates a conversation.
    # @return [Boolean]
    attr_accessor :preview_url

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['body'] = 'body'
      @_hash['preview_url'] = 'preview_url'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        preview_url
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(body = nil,
                   preview_url = false)
      @body = body unless body == SKIP
      @preview_url = preview_url unless preview_url == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      body = hash.key?('body') ? hash['body'] : SKIP
      preview_url = hash['preview_url'] ||= false

      # Create object from extracted values.
      Text.new(body,
               preview_url)
    end
  end
end
