# whats_app_cloud_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module WhatsAppCloudApi
  # UrlObject Model.
  class UrlObject < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :url

    # TODO: Write general description for this method
    # @return [PersonalInformationTypeEnum]
    attr_accessor :type

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['url'] = 'url'
      @_hash['type'] = 'type'
      @_hash
    end

    # An array for optional fields
    def optionals
      %w[
        url
        type
      ]
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(url = nil,
                   type = nil)
      @url = url unless url == SKIP
      @type = type unless type == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      url = hash.key?('url') ? hash['url'] : SKIP
      type = hash.key?('type') ? hash['type'] : SKIP

      # Create object from extracted values.
      UrlObject.new(url,
                    type)
    end
  end
end
