# whats_app_cloud_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module WhatsAppCloudApi
  # VerifyCodeRequest Model.
  class VerifyCodeRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The code you received after calling FROM_PHONE_NUMBER_ID/request_code.
    # @return [String]
    attr_accessor :code

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['code'] = 'code'
      @_hash
    end

    # An array for optional fields
    def optionals
      []
    end

    # An array for nullable fields
    def nullables
      []
    end

    def initialize(code = nil)
      @code = code unless code == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      code = hash.key?('code') ? hash['code'] : SKIP

      # Create object from extracted values.
      VerifyCodeRequest.new(code)
    end
  end
end
