# whats_app_cloud_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module WhatsAppCloudApi
  # Vertical.
  class VerticalEnum
    VERTICAL_ENUM = [
      # TODO: Write general description for UNDEFINED
      UNDEFINED = 'UNDEFINED'.freeze,

      # TODO: Write general description for OTHER
      OTHER = 'OTHER'.freeze,

      # TODO: Write general description for AUTO
      AUTO = 'AUTO'.freeze,

      # TODO: Write general description for BEAUTY
      BEAUTY = 'BEAUTY'.freeze,

      # TODO: Write general description for APPAREL
      APPAREL = 'APPAREL'.freeze,

      # TODO: Write general description for EDU
      EDU = 'EDU'.freeze,

      # TODO: Write general description for ENTERTAIN
      ENTERTAIN = 'ENTERTAIN'.freeze,

      # TODO: Write general description for EVENT_PLAN
      EVENT_PLAN = 'EVENT_PLAN'.freeze,

      # TODO: Write general description for FINANCE
      FINANCE = 'FINANCE'.freeze,

      # TODO: Write general description for GROCERY
      GROCERY = 'GROCERY'.freeze,

      # TODO: Write general description for GOVT
      GOVT = 'GOVT'.freeze,

      # TODO: Write general description for HOTEL
      HOTEL = 'HOTEL'.freeze,

      # TODO: Write general description for HEALTH
      HEALTH = 'HEALTH'.freeze,

      # TODO: Write general description for NONPROFIT
      NONPROFIT = 'NONPROFIT'.freeze,

      # TODO: Write general description for PROF_SERVICES
      PROF_SERVICES = 'PROF_SERVICES'.freeze,

      # TODO: Write general description for RETAIL
      RETAIL = 'RETAIL'.freeze,

      # TODO: Write general description for TRAVEL
      TRAVEL = 'TRAVEL'.freeze,

      # TODO: Write general description for RESTAURANT
      RESTAURANT = 'RESTAURANT'.freeze,

      # TODO: Write general description for NOT_A_BIZ
      NOT_A_BIZ = 'NOT_A_BIZ'.freeze
    ].freeze
  end
end
